spring:
  application:
    name: taxon-ws
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchRestClientAutoConfiguration
  lifecycle:
    timeout-per-shutdown-phase: 3s
  config:
    import: "optional:zookeeper:"
  cloud:
    zookeeper:
      enabled: false
elasticsearch:
  hosts: es9master.checklistbank.org:9200,esnine1.checklistbank.org:9200,esnine2.checklistbank.org:9200,esnine3.checklistbank.org:9200
  index:
    name: clbdev
    numShards: 8
    numReplicas: 1
  connectTimeout: 8000
  socketTimeout: 10000
datasource:
  url: jdbc:postgresql://localhost/clb
  password: postgres
  username: postgres
  hikari:
    poolName: taxon-ws
    maximumPoolSize: 4
    minimumIdle: 1
    idleTimeout: 120000
    connectionTimeout: 30000
