spring:
  application:
    name: taxon-ws
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.elasticsearch.ElasticsearchRestClientAutoConfiguration
  lifecycle:
    timeout-per-shutdown-phase: 3s
  config:
    import: "optional:zookeeper:"
  cloud:
    zookeeper:
      enabled: false
elasticsearch:
  hosts: localhost:9200
  index:
    name: clb
  connectTimeout: 8000
  socketTimeout: 10000
datasource:
  url: jdbc:postgresql://localhost/clb
  password: postgres
  username: postgres
  hikari:
    poolName: taxon-ws
    maximumPoolSize: 4
    minimumIdle: 1
    idleTimeout: 120000
    connectionTimeout: 30000
col:
  matchingUrl: https://api.gbif.org/v2/species/match/metadata?checklistKey=7ddf754f-d193-4cc9-b351-99906754a03b
  refresh-interval: PT1H
checklists:
  clbApi: https://api.checklistbank.org/
  clbUi: https://www.checklistbank.org/
registry:
  enabled: false
  api: https://api.gbif.org/v1/
  username: ${REGISTRY_USER:}
  appKey: ${REGISTRY_APP_KEY:}
  secret: ${REGISTRY_SECRET:}
sitemap:
  api: https://api.gbif.org/v2/experimental/
  portal: https://www.gbif.org/
monitoring:
  slow-request:
    enabled: true
    threshold-ms: 1000
  slow-sql:
    enabled: true
    threshold-ms: 500
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
      percentiles:
        http.server.requests: 0.5,0.95,0.99
